#!/usr/bin/env bash
# Regenerates starter/sql/starter.data.admin.sql: the /admin/ section (pages, translations, rights)
# taken from the demo base data, for the empty-site install. Run as root from the repository.
set -euo pipefail
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); S="$REPO/starter/sql"
T=$(mktemp -d /tmp/e213a.XXXX); trap '[ -s "$T/pid" ] && kill "$(cat "$T/pid")"; sleep 1; rm -rf "$T"' EXIT
mariadb-install-db --no-defaults --user=root --datadir="$T/data" --auth-root-authentication-method=socket --skip-test-db > /dev/null
mariadbd --no-defaults --user=root --datadir="$T/data" --socket="$T/s" --pid-file="$T/pid" --skip-networking &
Q() { mariadb --no-defaults --socket="$T/s" -u root --default-character-set=utf8 "$@"; }
for _ in $(seq 150); do Q -e 'SELECT 1' > /dev/null 2>&1 && break; sleep 0.2; done
Q -e 'CREATE DATABASE e CHARACTER SET utf8'
for f in starter.structure.sql starter.routines.sql starter.data.demo.sql starter.structure.fixes.sql modules.structure.sql; do
  Q e < "$S/$f"
done
IDS=$(Q -N e -e "WITH RECURSIVE t AS (SELECT smap_id FROM share_sitemap WHERE smap_segment = 'admin'
  AND smap_pid = (SELECT smap_id FROM share_sitemap WHERE smap_pid IS NULL LIMIT 1)
  UNION ALL SELECT s.smap_id FROM share_sitemap s JOIN t ON s.smap_pid = t.smap_id) SELECT GROUP_CONCAT(smap_id) FROM t")
ROOT=$(Q -N e -e "SELECT smap_id FROM share_sitemap WHERE smap_pid IS NULL LIMIT 1")
{
  echo "-- The /admin/ section for the empty site (generated by tools/gen-admin-sql.sh from starter.data.demo.sql)."
  echo "-- Import after modules.structure.sql and before modules.data.sql. The parent is the root page of site 1."
  echo "SET @root := (SELECT smap_id FROM share_sitemap WHERE smap_pid IS NULL LIMIT 1);"
  mariadb-dump --no-defaults --socket="$T/s" -u root --no-create-info --skip-triggers --compact --complete-insert \
    --where="smap_id IN ($IDS)" e share_sitemap share_sitemap_translation share_access_level \
    | sed "s/,$ROOT,/,@root,/g"
} > "$S/starter.data.admin.sql"
echo "written: $(grep -c 'INSERT INTO' "$S/starter.data.admin.sql") INSERT statements"
